version: '3.6'

services:
  
    api:
        build:
            context: ./
        container_name: cronos_api
        restart: always
        volumes:
            - "./:/usr/local/src/cti"
        ports:
            - "${API_PORT}:${API_PORT}"
        environment:
            DEBUG: ${DEBUG}
            RELOAD: ${RELOAD}
            API_HOST: ${API_HOST}
            API_PORT: ${API_PORT}
            DB_SERVER: ${MYSQL_SERVER}
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            DB_HOST_CTI: ${MYSQL_HOST_CTI}
            DB_HOST_ASTERISK: ${MYSQL_HOST_ASTERISK}
            DB_DATABASE_CTI: ${MYSQL_DATABASE_CTI}
            DB_DATABASE_ASTERISK: ${MYSQL_DATABASE_ASTERISK}
        
    db:
        image: mariadb:10.9.4
        container_name: cronos_db
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MARIADB_USER: ${MYSQL_USER}
            MARIADB_PASSWORD: ${MYSQL_PASSWORD}
            MARIADB_DATABASE: ${MYSQL_DATABASE_CTI}
        volumes:
            - "./db:/var/lib/mysql"
        ports:
            - "${DB_PORT}:${DB_PORT}"
       

    